// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/**
 * @title AuditGate
 * @notice World ID–gated audit request contract.
 *         Only verified humans (via World ID Orb credential) can trigger
 *         an on-chain audit request, which the CRE workflow listens for
 *         via a LogTrigger.
 *
 * @dev Uses the World ID Router contract for ZK proof verification.
 *      Nullifier tracking ensures each human can only request one audit
 *      per action (Sybil resistant).
 */

interface IWorldID {
    function verifyProof(
        uint256 root,
        uint256 groupId,
        uint256 signalHash,
        uint256 nullifierHash,
        uint256 externalNullifierHash,
        uint256[8] calldata proof
    ) external view;
}

contract AuditGate {

    // ── State ───────────────────────────────────────────────────────────────────

    IWorldID public immutable worldId;
    uint256  public immutable appId;
    uint256  public immutable actionId;
    address  public immutable owner;

    mapping(uint256 => bool) public usedNullifiers;

    // ── Events ──────────────────────────────────────────────────────────────────

    event AuditRequested(
        address indexed requester,
        uint256 timestamp,
        uint256 nullifierHash
    );

    // ── Constructor ─────────────────────────────────────────────────────────────

    /**
     * @param _worldId  Address of the World ID Router contract.
     *                  Sepolia: 0x469449f251692E0779667583026b5A1E99512157
     * @param _appId    Hashed app ID from the World Developer Portal.
     *                  Computed as: abi.encodePacked("app_<your_app_id>") hashed to field.
     * @param _actionId Hashed action string.
     *                  Computed as: abi.encodePacked("request-audit") hashed to field.
     */
    constructor(address _worldId, uint256 _appId, uint256 _actionId) {
        worldId  = IWorldID(_worldId);
        appId    = _appId;
        actionId = _actionId;
        owner    = msg.sender;
    }

    // ── Main Function ───────────────────────────────────────────────────────────

    /**
     * @notice Request a financial audit. Requires a valid World ID Orb proof.
     * @param root           Current merkle root of the World ID identity tree.
     * @param nullifierHash  Unique per-user per-action hash preventing double-signaling.
     * @param proof          The ZK proof generated by the IDKit widget.
     */
    function requestAudit(
        uint256 root,
        uint256 nullifierHash,
        uint256[8] calldata proof
    ) external {
        // 1. Ensure this nullifier hasn't been used (Sybil resistance)
        require(!usedNullifiers[nullifierHash], "Proof already used");

        // 2. Verify the World ID ZK proof via the Router
        worldId.verifyProof(
            root,
            1,                                        // groupId = 1 (Orb only)
            _hashToField(abi.encodePacked(msg.sender)), // signal = caller address
            nullifierHash,
            _externalNullifierHash(),
            proof
        );

        // 3. Mark nullifier as used
        usedNullifiers[nullifierHash] = true;

        // 4. Emit event — CRE LogTrigger listens for this
        emit AuditRequested(msg.sender, block.timestamp, nullifierHash);
    }

    /**
     * @notice Staging-only: request audit without World ID proof verification.
     * @dev    Only callable by the contract deployer. Used for hackathon demo
     *         where staging World ID proofs cannot be verified on-chain.
     *         In production, this function would be removed.
     */
    function requestAuditDev() external {
        require(msg.sender == owner, "Only owner");
        emit AuditRequested(msg.sender, block.timestamp, 0);
    }

    // ── Helpers ─────────────────────────────────────────────────────────────────

    /**
     * @dev Combines appId and actionId into the externalNullifierHash
     *      expected by the World ID Router.
     */
    function _externalNullifierHash() internal view returns (uint256) {
        return _hashToField(abi.encodePacked(appId, actionId));
    }

    /**
     * @dev Hashes arbitrary bytes to a field element (mod SNARK_SCALAR_FIELD).
     *      This matches World ID's hashToField() used in the frontend SDK.
     */
    function _hashToField(bytes memory data) internal pure returns (uint256) {
        return uint256(keccak256(data)) >> 8;
    }
}
